[package]
name = "bookdata"
version = "0.1.0"
authors = ["Michael Ekstrand <michaelekstrand@boisestate.edu>"]

[dependencies]
structopt = "0.2"
quick-xml = "^0.13.0"
flate2 = "1.0.6"
indicatif = "0.10.2"
postgres = "0.15.2"
postgres-binary-copy = "0.5.0"
ntriple = "0.1.1"
zip = "0.5.0"
log = "^0.4.0"
stderrlog = "^0.4.0"
derive_more = "0.9"
snap = "0.2.5"
