[package]
name = "bookdata"
version = "0.1.0"
authors = ["Michael Ekstrand <michaelekstrand@boisestate.edu>"]

[dependencies]
structopt = "0.2"
quick-xml = "0.12.0"
flate2 = "1.0.6"
indicatif = "0.10.2"
