name: bookdata
channels:
- mdekstrand
- defaults
- conda-forge  # last so it is not preferred
dependencies:
- python=3.7
- pip
- invoke
- docopt
- more-itertools
- psycopg2
- pandas
- numpy
- tqdm
- colorama
- seaborn
- sqlalchemy
- sqlparse
- rust>=1.32
- postgresql>=10
- requests
- html5lib
- dvc
- pip:
  - chromalog
  - natural
