name: bookdata
channels:
- mdekstrand
- defaults
dependencies:
- python=3.7
- pip
- invoke
- docopt
- more-itertools
- psycopg2
- numba
- pandas
- numpy
- tqdm
- colorama
- humanize
- seaborn
- sqlalchemy
- sqlparse
- rust>=1.32
- postgresql>=10
- requests
- html5lib
- wget
# DVC deps
- contextlib2
- gitpython
- configparser
- configobj
- pyyaml
- paramiko
- pillow
- ply
- pip:
  - chromalog
  - dvc[s3]>=0.49.2
