name: bookdata
channels:
- mdekstrand
- defaults
dependencies:
- python=3.7
- pip
- invoke
- more-itertools
- psycopg2
- numba
- pandas
- numpy
- tqdm
- colorama
- humanize
- rust>=1.32
- postgresql>=10
- pip:
  - chromalog
